language: cpp
sudo: false

matrix:
  include:

    - os: linux
      python: 2.7
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - gfortran
            - cmake
              # math libraries
            - libblas-dev
            - liblapack-dev
            - libopenblas-base
            - libopenblas-dev
            #- libatlas-dev
              # mpi
            - openmpi-bin
            - libopenmpi-dev
              # python library, development version
            - libpython2.7
              # boost
            - libboost-all-dev

    - os: linux
      python: 3.5
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - gfortran
              # math libraries
            - libblas-dev
            - liblapack-dev
            #- libatlas-base-dev
            #- libatlas-dev
            - libopenblas-base
            - libopenblas-dev
              # mpi
            - openmpi-bin
            - libopenmpi-dev
              # python library, development version
            - libpython2.7
              # boost
            - libboost-all-dev

    - os: osx
      osx_image: xcode6.4
      compiler: gcc
      env: SOURCES=homebrew

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew install cmake boost python gcc open-mpi
        pip install virtualenv
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        pip install --user virtualenv
        curl https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz
        export PATH=~/cmake-3.5.2-Linux-x86_64/bin:$PATH
        export LD_LIBARY_PATH=~/cmake-3.5.2-Linux-x86_64/lib:$LD_LIBRARY_PATH
    fi
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

script:
    # pep8 tests
  - pep8 --ignore E501 update.py
  - pep8 --ignore E501,E265 autocmake
    # unit tests
  - py.test -vv autocmake/*
  - py.test -vv test/test.py

notifications:
  email: false
